# This file is used to test the reproducibility of TB_annotation.R

# NOTE: set.seed() constrains the stochasticity of UMAP but cluster number assigned by kmeans will not be fixed
#       meaning that cluster labels will be consideredbased on the distance displayed in the heatmap generated by
#       each execution and the cluster numbers assigned by kmeans() DO NOT NECESSARILY infer cluster labeles
#       (e.g. blood vs. tissue)

# This file in used to annotate tissue-blood residents

set.seed(13351923)
library(ggplot2);
library(data.table);
library(Seurat)
library(Matrix)
library(ggplot2)
library(cowplot)
library(patchwork)
library(tidyr)
library(stringr)
library(dplyr)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(pheatmap)
library("RColorBrewer")
organism = "org.Hs.eg.db"
library(organism, character.only = TRUE)

library(clustree)

setwd("E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref")

'%!in%' <- function(x,y)!('%in%'(x,y))


# Read a file containing artificailly-mixed tissue-blood residents
# In PBMC scenario, use this data: "E:/Tays_workspace/data/data_merged_tissue_blood_residents_DEMO_noNKcellTissueBlood.rds"
data.artificial.TB <- readRDS("E:/Tays_workspace/data/data_merged_tissue_blood_residents_DEMO_noNKcellTissueBlood.rds")


# Filter to get data from M1 and pbmc8k for the analysis
data.artificial.TB <- subset(data.artificial.TB, subset = orig.ident %in% c("M1", "pbmc8k"))

###compartment assignment

data.artificial.TB.meta <- data.artificial.TB[[]]

data.artificial.TB.meta$compartment <- data.artificial.TB.meta$final_annotation

data.artificial.TB.meta$compartment[data.artificial.TB.meta$final_annotation == "T-cell" | data.artificial.TB.meta$final_annotation == "Monocyte"
                                    | data.artificial.TB.meta$final_annotation == "B-cell"] <- "Immune"

data.artificial.TB.meta$compartment[data.artificial.TB.meta$final_annotation == "Epithelial cell" | data.artificial.TB.meta$final_annotation == "Tissue stem cell"] <- "Non-immune"


## Assign ground truth for tissue-blood origins
list_tissue_origins <- c("M1")
list_blood_origins <- c("pbmc8k")

data.artificial.TB.meta$origin_groundtruth <- data.artificial.TB.meta$final_annotation
data.artificial.TB.meta$origin_groundtruth[data.artificial.TB.meta$orig.ident %in% list_tissue_origins] <- "Tissue"
data.artificial.TB.meta$origin_groundtruth[data.artificial.TB.meta$orig.ident %in% list_blood_origins] <- "Blood"

data.artificial.TB@meta.data <- data.artificial.TB.meta


# Load whole blood scRNA-seq data for a reference
# NOTE: This file is generated from: "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/new_pipeline/variant_analysis_4/PDAC_TBannotation_usingWholeBlood.R"
tabular_sapiens_blood_editedGeneNames_noduplicatedGenes <- readRDS("E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/new_pipeline/variant_analysis_4/data/Tabular_sapiens_blood_editedGeneNames_noduplicatedGenes_withLevel1Annotation.rds")

####### Perform blood-tissue annotation on (T-cells, monocyte, B cell)
data_forQuery <- data.artificial.TB

data_forQuery.immune <- subset(data_forQuery, subset = compartment == "Immune")

######## NOTE: This step is run on Server due to high computational cost

data_list <- c(tabular_sapiens_blood_editedGeneNames_noduplicatedGenes, data_forQuery.immune)

wholeblood_data.anchor <- FindIntegrationAnchors(object.list = data_list, dims = 1:30, anchor.features = 3000)
wholeblood.integrated <- IntegrateData(anchorset = wholeblood_data.anchor, dims = 1:30)

wholeblood.integrated <- ScaleData(wholeblood.integrated, verbose = FALSE)
wholeblood.integrated <- RunPCA(wholeblood.integrated, npcs = 30, verbose = FALSE)
wholeblood.integrated <- RunUMAP(wholeblood.integrated, reduction = "pca", dims = 1:30, n.components = 10)
wholeblood.integrated <- FindNeighbors(wholeblood.integrated, reduction = "pca", dims = 1:30)
wholeblood.integrated <- FindClusters(wholeblood.integrated, resolution = 0.4)

# saveRDS(wholeblood.integrated, "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/wholeblood_immune_withSimulatedData_integrated_forTBannotation_noNKcellTissueBlood.rds")

# Perform tissue and blood immune cells identification
wholeblood.integrated <- readRDS("E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/wholeblood_immune_withSimulatedData_integrated_forTBannotation_noNKcellTissueBlood.rds")


# Define query and reference on common immune cell types
## Query side: T-cell, B-cell, Monocyte
## Reference side: T-cell, B cell, monocyte

list_common_immune_query <- c("T-cell", "B-cell", "Monocyte")
list_common_immune_reference <- c("T-cell", "B cell", "monocyte")


wholeblood.integrated_meta <- wholeblood.integrated@meta.data

wholeblood.integrated_meta$annotation_query_ref <- rep(NA, nrow(wholeblood.integrated_meta))

wholeblood.integrated_meta$annotation_query_ref[wholeblood.integrated_meta$final_annotation == "T-cell"] <- "Query T-cell"
wholeblood.integrated_meta$annotation_query_ref[wholeblood.integrated_meta$final_annotation == "B-cell"] <- "Query B cell"
wholeblood.integrated_meta$annotation_query_ref[wholeblood.integrated_meta$final_annotation == "Monocyte"] <- "Query monocyte"

wholeblood.integrated_meta$annotation_query_ref[wholeblood.integrated_meta$level1_annotation == "T-cell"] <- "Ref T-cell"
wholeblood.integrated_meta$annotation_query_ref[wholeblood.integrated_meta$level1_annotation == "B cell"] <- "Ref B cell"
wholeblood.integrated_meta$annotation_query_ref[wholeblood.integrated_meta$level1_annotation == "monocyte"] <- "Ref monocyte"

wholeblood.integrated_meta$orig.ident[wholeblood.integrated_meta$final_annotation == "T-cell"] <- "Query"
wholeblood.integrated_meta$orig.ident[wholeblood.integrated_meta$final_annotation == "B-cell"] <- "Query"
wholeblood.integrated_meta$orig.ident[wholeblood.integrated_meta$final_annotation == "Monocyte"] <- "Query"

wholeblood.integrated_meta$orig.ident[wholeblood.integrated_meta$level1_annotation == "T-cell"] <- "Ref"
wholeblood.integrated_meta$orig.ident[wholeblood.integrated_meta$level1_annotation == "B cell"] <- "Ref"
wholeblood.integrated_meta$orig.ident[wholeblood.integrated_meta$level1_annotation == "monocyte"] <- "Ref"

wholeblood.integrated.common.immune <- wholeblood.integrated

wholeblood.integrated.common.immune@meta.data <-  wholeblood.integrated_meta

list_annotation_query_ref <- unlist(unique(wholeblood.integrated.common.immune$annotation_query_ref))
list_annotation_query_ref <-  list_annotation_query_ref[is.na(list_annotation_query_ref) == FALSE]

wholeblood.integrated.common.immune <- subset(wholeblood.integrated.common.immune,
                                              subset = annotation_query_ref %in% list_annotation_query_ref)

# Extract umap embedding 1-10
wholeblood.integrated.common.immune_subset_xy <- wholeblood.integrated.common.immune[["umap"]]@cell.embeddings
wholeblood.integrated.common.immune_subset_meta <- wholeblood.integrated.common.immune[[]]
wholeblood.integrated.common.immune_subset_meta <- wholeblood.integrated.common.immune_subset_meta[, c("orig.ident", "annotation_query_ref")]
wholeblood.integrated.common.immune_subset_meta <- wholeblood.integrated.common.immune_subset_meta[row.names(wholeblood.integrated.common.immune_subset_meta), ]
table(row.names(wholeblood.integrated.common.immune_subset_meta) == row.names(wholeblood.integrated.common.immune_subset_xy))
wholeblood.integrated.common.immune_subset_meta_2 <- cbind(wholeblood.integrated.common.immune_subset_meta, wholeblood.integrated.common.immune_subset_xy)

###plot distance matrix and kemans cluster based on umap 1-10
library(RColorBrewer)
my.break1 <- seq(0, 15)
my.color1 <- colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(length(my.break1))

my.break2 <- seq(0, 20)
my.color2 <- colorRampPalette(rev(brewer.pal(n = 14, name = "RdYlBu")))(length(my.break1))

my.break3 <- seq(0, 15)
my.color3 <- colorRampPalette(rev(brewer.pal(n = 4, name = "RdYlBu")))(length(my.break1))


# Perform blood and tissue-resident immune cell separation on common cell types
list_annotation_query_ref

DimPlot(wholeblood.integrated.common.immune, group.by = "annotation_query_ref", split.by = "orig.ident")

#############
ct = "T-cell"
temp1 <- wholeblood.integrated.common.immune_subset_meta_2[grep(ct, wholeblood.integrated.common.immune_subset_meta_2$annotation_query_ref), ]

###Use only cells within range to avoid cluster error: -3.00 < UMAP 1 < 0.00; -5.80 < UMAP 2 < 4.55
temp1 <- temp1[temp1$UMAP_1 > -3.00 & temp1$UMAP_1 < 0.00 & temp1$UMAP_2 > -5.80 & temp1$UMAP_2 < 4.55, ]
ref_cid <- row.names(temp1[temp1$orig.ident == "Ref", ])
query_cid <- row.names(temp1[temp1$orig.ident == "Query", ])
temp2 <- as.matrix(temp1[, 3:12])
temp3 <- as.matrix(dist(temp2))
temp4 <- temp3[query_cid, ref_cid]

km.res <- kmeans(temp4, 2, nstart = 25)
km.res2 <- cbind(temp4, cluster = km.res$cluster)
km.res3 <- km.res2[, "cluster", drop = F]
km.res3 <- as.data.frame(km.res3)
km.res3 <- km.res3[order(km.res3$cluster), , drop = F]
km.res3$cluster <- as.factor(km.res3$cluster)
temp4 <- temp4[row.names(km.res3), ]

pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_Tcells_UMAP_d10_query_ref_dist.pdf", width = 15, height = 6)
print(pheatmap(temp4, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, color = my.color1, breaks = my.break1))
dev.off()

###median distance for each query
temp4 <- as.data.frame(temp4)
temp4$dist_median = rowMedians(as.matrix(temp4[,c(-1)]))
temp5 <- temp4[, "dist_median", drop = F]
pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_Tcells_UMAP_d10_query_ref_dist_median.pdf", width = 4, height = 6)
print(pheatmap(temp5, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, cluster_cols = FALSE, color = my.color1, breaks = my.break1))
dev.off()

pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_Tcells_UMAP_d10_query_ref_dist_median_nobreak.pdf", width = 4, height = 6)
print(pheatmap(temp5, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, cluster_cols = FALSE))
dev.off()

##Assign tissue and blood origin based on distance calculated
km.res3 <- as.data.frame(km.res3, drop = F)
km.res3$origin_tb <- rep("Null", dim(km.res3)[1])
km.res3$origin_tb[km.res3$cluster == 1] <- "Blood"
km.res3$origin_tb[km.res3$cluster == 2] <- "Tissue"

save(km.res3, file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_Tcells_UMAP_d10_query_ref_dist.RData")

############# 
ct = "monocyte"

temp1 <- wholeblood.integrated.common.immune_subset_meta_2[grep(ct, wholeblood.integrated.common.immune_subset_meta_2$annotation_query_ref), ]

###Use only cells within range to avoid cluster error: -3.10 < UMAP 1 < 6.78; -5.92 < UMAP 2 < 5.80
temp1 <- temp1[temp1$UMAP_1 > -3.10 & temp1$UMAP_1 < 6.78 & temp1$UMAP_2 > -5.92 & temp1$UMAP_2 < 5.80, ]
ref_cid <- row.names(temp1[temp1$orig.ident == "Ref", ])
query_cid <- row.names(temp1[temp1$orig.ident == "Query", ])
temp2 <- as.matrix(temp1[, 3:12])
temp3 <- as.matrix(dist(temp2))
temp4 <- temp3[query_cid, ref_cid]

km.res <- kmeans(temp4, 2, nstart = 25)
km.res2 <- cbind(temp4, cluster = km.res$cluster)
km.res3 <- km.res2[, "cluster", drop = F]
km.res3 <- as.data.frame(km.res3)
km.res3 <- km.res3[order(km.res3$cluster), , drop = F]
km.res3$cluster <- as.factor(km.res3$cluster)
temp4 <- temp4[row.names(km.res3), ]

pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_monocyte_UMAP_d10_query_ref_dist.pdf", width = 15, height = 6)
print(pheatmap(temp4, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, color = my.color1, breaks = my.break1))
dev.off()

###median distance for each query
temp4 <- as.data.frame(temp4)
temp4$dist_median = rowMedians(as.matrix(temp4[,c(-1)]))
temp5 <- temp4[, "dist_median", drop = F]
pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_monocyte_UMAP_d10_query_ref_dist_median.pdf", width = 4, height = 6)
print(pheatmap(temp5, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, cluster_cols = FALSE, color = my.color1, breaks = my.break1))
dev.off()

pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_monocyte_UMAP_d10_query_ref_dist_median_nobreak.pdf", width = 4, height = 6)
print(pheatmap(temp5, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, cluster_cols = FALSE))
dev.off()

##Assign tissue and blood origin based on distance calculated
km.res3 <- as.data.frame(km.res3, drop = F)
km.res3$origin_tb <- rep("Null", dim(km.res3)[1])
km.res3$origin_tb[km.res3$cluster == 1] <- "Tissue"
km.res3$origin_tb[km.res3$cluster == 2] <- "Blood"

save(km.res3, file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_monocyte_UMAP_d10_query_ref_dist.RData")

############# 
ct = "B cell"

temp1 <- wholeblood.integrated.common.immune_subset_meta_2[grep(ct, wholeblood.integrated.common.immune_subset_meta_2$annotation_query_ref), ]

###Use only cells within range to avoid cluster error: -2.80 < UMAP 1 < 0.04; -6.01 < UMAP 2 < 4.06
temp1 <- temp1[temp1$UMAP_1 > -2.80 & temp1$UMAP_1 < 0.04 & temp1$UMAP_2 > -6.01 & temp1$UMAP_2 < 4.06, ]
ref_cid <- row.names(temp1[temp1$orig.ident == "Ref", ])
query_cid <- row.names(temp1[temp1$orig.ident == "Query", ])
temp2 <- as.matrix(temp1[, 3:12])
temp3 <- as.matrix(dist(temp2))
temp4 <- temp3[query_cid, ref_cid]

km.res <- kmeans(temp4, 2, nstart = 25)
km.res2 <- cbind(temp4, cluster = km.res$cluster)
km.res3 <- km.res2[, "cluster", drop = F]
km.res3 <- as.data.frame(km.res3)
km.res3 <- km.res3[order(km.res3$cluster), , drop = F]
km.res3$cluster <- as.factor(km.res3$cluster)
temp4 <- temp4[row.names(km.res3), ]

pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_bcell_UMAP_d10_query_ref_dist.pdf", width = 15, height = 6)
print(pheatmap(temp4, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, color = my.color1, breaks = my.break1))
dev.off()

###median distance for each query
temp4 <- as.data.frame(temp4)
temp4$dist_median = rowMedians(as.matrix(temp4[,c(-1)]))
temp5 <- temp4[, "dist_median", drop = F]
pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_bcell_UMAP_d10_query_ref_dist_median.pdf", width = 4, height = 6)
print(pheatmap(temp5, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, cluster_cols = FALSE, color = my.color1, breaks = my.break1))
dev.off()

pdf(file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_bcell_UMAP_d10_query_ref_dist_median_nobreak.pdf", width = 4, height = 6)
print(pheatmap(temp5, annotation_names_col = FALSE, annotation_names_row = FALSE, show_rownames = FALSE, show_colnames = FALSE, main = paste0(ct), annotation_row = km.res3, cluster_rows = FALSE, cluster_cols = FALSE))
dev.off()


##Assign tissue and blood origin based on distance calculated
km.res3 <- as.data.frame(km.res3, drop = F)
km.res3$origin_tb <- rep("Null", dim(km.res3)[1])
km.res3$origin_tb[km.res3$cluster == 1] <- "Blood"
km.res3$origin_tb[km.res3$cluster == 2] <- "Tissue"

save(km.res3, file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_bcell_UMAP_d10_query_ref_dist.RData")


##collect all data
temp_meta <- NULL

load("E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_Tcells_UMAP_d10_query_ref_dist.RData", verbose = T)
temp_meta <- rbind(temp_meta, km.res3)
load("E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_monocyte_UMAP_d10_query_ref_dist.RData", verbose = T)
temp_meta <- rbind(temp_meta, km.res3)
load("E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/Wholeblood_bcell_UMAP_d10_query_ref_dist.RData", verbose = T)
temp_meta <- rbind(temp_meta, km.res3)


save(temp_meta, file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/tissue_blood_annotation_usingWholeBlood.RData")


### pull results and annotate tissue and blood origin
data_TB_annotation <- data.artificial.TB


data_TB_annotation_meta <- data_TB_annotation@meta.data

### tissue and blood origin assignment
data_TB_annotation_meta_1 <- data_TB_annotation_meta[!(row.names(data_TB_annotation_meta) %in% row.names(temp_meta)), ]
data_TB_annotation_meta_1$TB_origin_wholeblood <- rep("Undetermined", dim(data_TB_annotation_meta_1)[1])

data_TB_annotation_meta_1$TB_origin_wholeblood[data_TB_annotation_meta_1$compartment == "Non-immune"] <- "Tissue"

data_TB_annotation_meta_2 <- data_TB_annotation_meta_1[, "TB_origin_wholeblood", drop = F]

temp_meta <- temp_meta[, "origin_tb", drop = F]
colnames(temp_meta) <- "TB_origin_wholeblood"

temp_meta <- rbind(temp_meta, data_TB_annotation_meta_2)

temp_meta <- temp_meta[row.names(data_TB_annotation_meta), , drop = F]

data_TB_annotation[["TB_origin_wholeblood"]] <- temp_meta$TB_origin_wholeblood

saveRDS(data_TB_annotation, file = "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/data_merged_tissue_blood_residents_DEMO_TB_TuN_annotation_usingWholeblood.rds")

write.csv(data_TB_annotation@meta.data, "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/meta_data_merged_tissue_blood_residents_DEMO_TB_TuN_annotation_usingWholeblood.csv")

# Write out predictions
## T-cell
data_TB_annotation_tcell <- subset(data_TB_annotation, subset = final_annotation == "T-cell")
write.csv(data_TB_annotation_tcell@meta.data, "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/meta_data_merged_tissue_blood_residents_DEMO_TB_TuN_annotation_usingWholeblood_tcell.csv")

## Monocyte
data_TB_annotation_monocyte <- subset(data_TB_annotation, subset = final_annotation == "Monocyte")
write.csv(data_TB_annotation_monocyte@meta.data, "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/meta_data_merged_tissue_blood_residents_DEMO_TB_TuN_annotation_usingWholeblood_monocyte.csv")

## B-cell
data_TB_annotation_Bcell <- subset(data_TB_annotation, subset = final_annotation == "B-cell")
write.csv(data_TB_annotation_Bcell@meta.data, "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/meta_data_merged_tissue_blood_residents_DEMO_TB_TuN_annotation_usingWholeblood_Bcell.csv")

## Combined common immune cells
data_TB_annotation_commonImmune <- subset(data_TB_annotation, subset = final_annotation %in% c("T-cell", "Monocyte", "B-cell"))
write.csv(data_TB_annotation_commonImmune@meta.data, "E:/Tays_workspace/Demultiplexing_PDAC_new_analysis/artificial_tissue_blood_mixing_wholeblood_ref/results/iteration_4/meta_data_merged_tissue_blood_residents_DEMO_TB_TuN_annotation_usingWholeblood_commonImmune.csv")










