#' Plot
#' @description
#' An object with functions that help generate plots
#'
#' @section Objects:
#' - \code{\link[=Plot.Umap]{Plot$Umap}}
#' - \code{\link[=Plot.Bar]{Plot$Bar}}
#' - \code{\link[=Plot.Heatmap]{Plot$Heatmap}}
#'
#' @export
Plot <- new.env()

#' Plot$Umap
#' @name Plot.Umap
#' @description
#' An object with functions that help generate UMAP plots
#'
#' @section Functions:
#' - \code{\link[=Plot.Umap.run]{Plot$Umap$run}}
#' - \code{\link[=Plot.Umap.runIfNotExists]{Plot$Umap$runIfNotExists}}
#' - \code{\link[=Plot.Umap.doTissueBlood]{Plot$Umap$doTissueBlood}}
#'
Plot$Umap <- new.env()

#' Plot$Umap$run
#' @name Plot.Umap.run
#' @description
#' Run UMAP on a Seurat object
#'
#' @param data Seurat object
#' @return UMAP calculated data
Plot$Umap$run <- function(data) {
  # TODO pipe
  data <- Seurat::NormalizeData(data)
  data <- Seurat::FindVariableFeatures(data, nfeatures = 3000)
  data <- Seurat::ScaleData(data)
  data <- Seurat::RunPCA(data, npcs = 30)
  data <-
    Seurat::RunUMAP(
      data,
      reduction = "pca",
      dims = 1:30,
      n.components = 10
    )
  return(data)
}

#' Plot$Umap$runIfNotExists
#' @name Plot.Umap.runIfNotExists
#' @description
#' Run UMAP on a Seurat object, if not already run
#'
#' @param data Seurat object
#' @return UMAP calculated data
Plot$Umap$runIfNotExists <- function(data) {
  if (is.null(data@reductions$umap)) {
    data <- Plot$Umap$run(data)
  }
  return(data)
}

#' Plot$Umap$doTissueBlood
#' @name Plot.Umap.doTissueBlood
#' @description
#' Generate UMAP plots, w/ and w/o labels, w/ and w/o tissue blood annotation,
#' w/ and w/o cell types that are not of interests
#'
#' @param config Dataset config
#' @param data Seurat object
#'
#' @return List of plots
Plot$Umap$doTissueBlood <- function(config, data) {
  data_sub <- Utils$subsetCellTypesInConfig(config, data)
  plots <- list(
    Seurat::DimPlot(data, reduction = "umap", group.by = config$ann_col),
    Seurat::DimPlot(
      data,
      reduction = "umap",
      group.by = config$ann_col,
      label = T
    ),
    Seurat::DimPlot(
      data,
      reduction = "umap",
      group.by = config$ann_col,
      split.by = "orig.ident"
    ),
    Seurat::DimPlot(
      data,
      reduction = "umap",
      group.by = config$ann_col,
      split.by = "orig.ident",
      label = T
    ),
    Seurat::DimPlot(
      data_sub,
      reduction = "umap",
      group.by = config$ann_col,
      split.by = "orig.ident"
    ),
    Seurat::DimPlot(
      data_sub,
      reduction = "umap",
      group.by = config$ann_col,
      split.by = "orig.ident",
      label = T
    )
  )
  return(plots)
}

#' Plot$Bar
#' @name Plot.Bar
#' @description
#' An object with functions that help generate bar plots
#'
#' @section Functions:
#' - \code{\link[=Plot.Bar.doCellTypeProportion]{Plot$Bar$doCellTypeProportion}}
#'
Plot$Bar <- new.env()

#' Plot$Bar$doCellTypeProportion
#' @name Plot.Bar.doCellTypeProportion
#' @description
#' Generate barplots for cell type proportion of both blood and tissue resident
#' cells, w/ and w/o cell types that are not of interests
#'
#' @param config Dataset config
#' @param data Seurat object
#'
#' @return List of plots
Plot$Bar$doCellTypeProportion <- function(config, data) {
  # Helper function that does the plot
  # proportions should be a dataframe generated by Utils$calcCellTypeProportion,
  # which has three columns: cellType, proportion and x
  # FIXME proportion column names are hard coded
  plotHelper <- function(proportions) {
    # Color palettes
    # TODO Improve colors
    colors = c(
      RColorBrewer::brewer.pal(name = "Set1", n = 9),
      RColorBrewer::brewer.pal(name = "Set3", n = 12),
      RColorBrewer::brewer.pal(name = "Set2", n = 8),
      RColorBrewer::brewer.pal(name = "Paired", n = 12),
      RColorBrewer::brewer.pal(name = "Dark2", n = 8),
      RColorBrewer::brewer.pal(name = "Accent", n = 8)
    )
    # FIXME Repeat twice just to avoid not enough colors error
    colors = c(colors, colors)

    p <- ggplot2::ggplot(proportions,
                         ggplot2::aes(x = x, y = proportion, fill = cellType)) +
      ggplot2::geom_bar(stat = "identity", position = "stack") +
      ggplot2::theme_minimal() +
      ggplot2::labs(title = "Proportion of Cell Types", x = "", y = "Proportion") +
      ggplot2::theme(
        axis.text.x = ggplot2::element_blank(),
        axis.ticks.x = ggplot2::element_blank()
      ) +
      ggplot2::scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
      ggplot2::scale_fill_manual(values = colors) +
      ggplot2::facet_wrap(~ orig.ident, ncol = length(proportions))
    return(p)
  }

  plots <- list()

  # Calculate cell type proportion for all cell types
  proportions_all <- Utils$calcCellTypeProportion(data, config$ann_col)
  subset_data_tissue <- subset(data, subset = orig.ident == "Tissue")
  proportions_tissue <- Utils$calcCellTypeProportion(subset_data_tissue, config$ann_col)
  subset_data_blood <- subset(data, subset = orig.ident == "Blood")
  proportions_blood <- Utils$calcCellTypeProportion(subset_data_blood, config$ann_col)

  # Plot bar plot for all cell types
  proportions_list <- list(proportions_all, proportions_tissue, proportions_blood)
  combined_proportions <- do.call(rbind, proportions_list)
  proportions_category = c("All", "Tissue", "Blood")
  combined_proportions$orig.ident <- factor(rep(proportions_category, sapply(proportions_list, nrow)), levels = proportions_category)

  plots <- append(plots, list(plotHelper(combined_proportions)))

  # Calculate cell type proportion for cell types of interests
  subset_data_tissue <- Utils$subsetCellTypesInConfig(config, subset_data_tissue)
  proportions_tissue <- Utils$calcCellTypeProportion(subset_data_tissue, config$ann_col)
  subset_data_blood <- Utils$subsetCellTypesInConfig(config, subset_data_blood)
  proportions_blood <- Utils$calcCellTypeProportion(subset_data_blood, config$ann_col)

  # Plot bar plot for cell types of interests
  proportions_list <- list(proportions_tissue, proportions_blood)
  combined_proportions <- do.call(rbind, proportions_list)
  proportions_category = c("Tissue", "Blood")
  combined_proportions$orig.ident <- factor(rep(proportions_category, sapply(proportions_list, nrow)), levels = proportions_category)

  plots <- append(plots, list(plotHelper(combined_proportions)))

  return(plots)

}

#' Plot$Heatmap
#' @name Plot.Heatmap
#' @description
#' An object with functions that help generate heatmap plots
#'
#' @section Functions:
#' - \code{\link[=Plot.Heatmap.buildTissueBloodProportion]{Plot$Heatmap$buildTissueBloodProportion}}
#' - \code{\link[=Plot.Heatmap.buildCellTypeProportion]{Plot$Heatmap$buildCellTypeProportion}}
#' - \code{\link[=Plot.Heatmap.doProportion]{Plot$Heatmap$doProportion}}
#'
Plot$Heatmap <- new.env()

#' Plot$Heatmap$buildTissueBloodProportion
#' @name Plot.Heatmap.buildTissueBloodProportion
#' @description
#' Build tissue-blood proportion dataframes for a list of datasets. Tissue-blood
#' annotated data must be stored as `data/${config$name}_tb_annotated.rds`.
#'
#' @param config List of dataset configs
#' @return 2 tissue-blood percentage dataframe, 1 for tissue and 1 for blood
Plot$Heatmap$buildTissueBloodProportion <- function(configs) {
  # Obtain a list of all unioned cell types
  all_cell_types <- Values$common_immune_cells
  # Init dataframes
  blood_df <-
    as.data.frame(matrix(nrow = length(configs), ncol = length(all_cell_types)))
  tissue_df <-
    as.data.frame(matrix(nrow = length(configs), ncol = length(all_cell_types)))
  colnames(blood_df) <- all_cell_types
  colnames(tissue_df) <- all_cell_types

  # Gather tissue blood annotated data and calculate proportion for each dataset
  for (i in 1:length(configs)) {
    config <- configs[[i]]
    Logger$info(paste("Reading tissue-blood annotated data:", config$name))
    # FIXME This is hard-coded
    data <-
      readRDS(paste0("./data/", config$name, "_tb_annotated.rds"))
    meta <- data@meta.data
    # Create a symbol for `config$ann_col`, so that one can use `!!ann_col` for
    # column access in dplyr
    ann_col <- sym(config$ann_col)
    # Subset data for cell types of interests
    meta <- meta %>% filter(!!ann_col %in% names(config$cell_types))
    # TODO Utils
    # Count occurrence grouped by cell type
    total_counts <- meta %>% count(!!ann_col)
    # Count occurrence grouped by cell type and is annotated as "Blood", rename
    # count column name as "blood_count"
    blood_counts <- meta %>%
      filter(orig.ident == "Blood") %>%
      count(!!ann_col) %>%
      rename(blood_count = n)
    # Count occurrence grouped by cell type and is annotated as "Tissue", rename
    # count column name as "tissue_count"
    tissue_counts <- meta %>%
      filter(orig.ident == "Tissue") %>%
      count(!!ann_col) %>%
      rename(tissue_count = n)
    # Merge total counts with blood and tissue counts dataframe, fill NA with 0
    merged_counts <- total_counts %>%
      left_join(blood_counts, by = config$ann_col) %>%
      left_join(tissue_counts, by = config$ann_col) %>%
      tidyr::replace_na(list(blood_count = 0, tissue_count = 0))
    # Divide blood/tissue counts by total and convert to percentage, save to
    # columns "blood_percentage" and "tissue_percentage"
    # TODO Total count already calculated, do not add again
    proportion_df <- merged_counts %>%
      mutate(
        blood_percentage = (blood_count / (blood_count + tissue_count)) * 100,
        tissue_percentage = (tissue_count / (blood_count + tissue_count)) * 100
      )
    # Split joint dataframe to two
    # TODO Return a single dataframe instead of two
    for (cell_type in all_cell_types) {
      # TODO Checking existence is not necessary, as dataframe is already
      # calculated from cell type of interests
      if (cell_type %in% proportion_df[[config$ann_col]]) {
        blood_df[i, cell_type] <-
          proportion_df[proportion_df[[config$ann_col]] == cell_type, "blood_percentage"]
        tissue_df[i, cell_type] <-
          proportion_df[proportion_df[[config$ann_col]] == cell_type, "tissue_percentage"]
      }
    }
    # Assign dataset name as row name
    row.names(blood_df)[[i]] <- config$name
    row.names(tissue_df)[[i]] <- config$name
  }
  return(list(blood = blood_df, tissue = tissue_df))
}

#' Plot$Heatmap$buildCellTypeProportion
#' @name Plot.Heatmap.buildCellTypeProportion
#' @description
#' Build cell type proportion dataframes for a list of datasets. Tissue-blood
#' annotated data must be stored as `data/${config$name}_tb_annotated.rds`.
#'
#' @param config List of dataset configs
#' @return 2 cell type percentage dataframe, 1 for tissue and 1 for blood
Plot$Heatmap$buildCellTypeProportion <- function(configs) {
  # FIXME Too many repeating code
  # Obtain a list of all unioned cell types
  all_cell_types <- Values$common_immune_cells
  # Init dataframes
  blood_df <-
    as.data.frame(matrix(nrow = length(configs), ncol = length(all_cell_types)))
  tissue_df <-
    as.data.frame(matrix(nrow = length(configs), ncol = length(all_cell_types)))
  colnames(blood_df) <- all_cell_types
  colnames(tissue_df) <- all_cell_types
  # Get a list of dataset names
  # TODO f
  dataset_names <- lapply(configs, function(config) {
    return(config$name)
  })
  row.names(blood_df) <- dataset_names
  row.names(tissue_df) <- dataset_names

  # Gather tissue blood annotated data and calculate proportion for each dataset
  for (i in 1:length(configs)) {
    config <- configs[[i]]
    Logger$info(paste("Reading tissue-blood annotated data:", config$name))
    # FIXME This is hard-coded
    data <-
      readRDS(paste0("./data/", config$name, "_tb_annotated.rds"))
    meta <- data@meta.data
    # Create a symbol for `config$ann_col`, so that one can use `!!ann_col` for
    # column access in dplyr
    ann_col <- sym(config$ann_col)
    # Subset data for cell types of interests
    meta <- meta %>% filter(!!ann_col %in% names(config$cell_types))
    # Drop cell types with zero occurrences
    # TODO f
    if (is.factor(meta[[config$ann_col]])) {
      meta[[config$ann_col]] <- droplevels(meta[[config$ann_col]])
    }
    # Calculate cell type percentage using `prop.table(table())`
    # TODO Utils
    blood_meta <- meta %>% filter(orig.ident == "Blood")
    tissue_meta <- meta %>% filter(orig.ident == "Tissue")
    blood_percentage <- prop.table(table(blood_meta[[config$ann_col]])) * 100
    tissue_percentage <- prop.table(table(tissue_meta[[config$ann_col]])) * 100
    # Assign percentage to corresponding columns
    blood_df[i, names(blood_percentage)] <- blood_percentage
    tissue_df[i, names(tissue_percentage)] <- tissue_percentage
  }
  return(list(blood = blood_df, tissue = tissue_df))
}

#' Plot$Heatmap$doProportion
#' @name Plot.Heatmap.doProportion
#' @description
#' Generate percentage proportion heatmap plots
#'
#' @param df Proportion dataframe, dataset by cell type
#' @param title Plot title, default empty string
#' @param label If true, label heatmap cells with values. Default true
#'
#' @return Plot object
Plot$Heatmap$doProportion <- function(df, title = "", label = T) {
  # Create a new column that has dataset names
  df$dataset <- row.names(df)
  # Define dataset column as factor, so that ggplot will treat x axis as ordered
  df$dataset <- factor(df$dataset, levels = df$dataset)
  # Gather dataframe for ggplot
  df <-
    tidyr::gather(df, key = "cell_type", value = "percentage", -dataset)
  # Plot the heatmap
  p <-
    ggplot2::ggplot(df, ggplot2::aes(x = dataset, y = cell_type, fill = percentage)) +
    ggplot2::geom_tile() +
    ggplot2::scale_fill_gradientn(
      colours = RColorBrewer::brewer.pal(9, "YlOrRd"),
      na.value = "white",
      limits = c(0, 100)
    ) +
    ggplot2::labs(x = "Dataset", y = "Cell Type") +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
      text = ggplot2::element_text(size = 20)
    ) +
    ggplot2::ggtitle(title)
  # Add label
  if (label) {
    p <- p + ggplot2::geom_text(
      ggplot2::aes(label = sprintf("%.1f", percentage)),
      color = ifelse(df$percentage > 50, "white", "black"),
      size = 8
    )
  }
  return(p)
}
